defmodule Commentator.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def change do
    alter table(:users) do
      add :first_name, :text
      add :last_name, :text
    end

    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :text, :text, null: false
      add :closed?, :boolean, null: false, default: false
      add :deleted?, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end
end
