name: develop CI/CD

on:
  push:
    branches:
      - develop

jobs:
  dev-job:
    runs-on: ubuntu-latest
    container: elixir:1.12-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add build deps
        run: apt-get update && apt-get install -y --no-install-recommends build-essential git nodejs npm && mix do local.hex --force, local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Run Credo
        run: mix credo

      - name: Run Sobelow
        run: mix sobelow

      - name: Compile for Tests
        run: MIX_ENV=test mix compile

      - name: Run Tests
        run: mix test
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432

  docker:
    needs: dev-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build & Push to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.GITHUB_USERNAME }}
          PASSWORD: ${{ secrets.PUSH_TOKEN }}
          REGISTRY: "ghcr.io"
          TAG_NAME: "dev"
          LATEST: "true"
